# Defines system-level paths (ONLY immutable structure).

artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_data_dir: data/processed
  financial_data_file: financial_statements_training.csv
  pd_data_file: pd_training.csv
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion
  preprocessor_path: artifacts/data_transformation/preprocessor.pkl

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  val_data_path: artifacts/data_transformation/val.csv
  model_name: acras_rf_model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/acras_rf_model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
  experiment_name: "ACRAS_Risk_Assessment"
  registered_model_name: "ACRAS_RandomForest_v1"
  mlflow_model_name: "acras_risk_model"

model_registration:
  root_dir: artifacts/model_registration
  model_path: artifacts/model_trainer/acras_rf_model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
  model_name: "ACRAS_RandomForest_v1"
