# Defines system-level paths (ONLY immutable structure).

artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_data_dir: data/raw
  financial_data_file: financial_statements_training.csv # Starting with training set for now
  pd_data_file: pd_training.csv
  unzip_dir: artifacts/data_ingestion
