# Defines hyperparameters (ONLY tunable values).

data_split:
  test_size: 0.15
  val_size: 0.15
  random_state: 42

model_params:
  n_estimators: 300
  min_samples_leaf: 5
  class_weight: balanced
  n_jobs: -1

mlflow:
  uri: "http://127.0.0.1:5000"

registration_params:
  min_roc_auc: 0.60
